<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ref_2ndNews</name>
   <tag></tag>
   <elementGuidId>1f635d22-4d33-405b-9b87-2d1c228fc218</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='___gcse_0']/div/div/div/div[5]/div[2]/div/div/div/div[2]/div/div/div/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'gs-title' and (text() = 'TikTok Shop Ditutup Hari Ini, &quot;Seller&quot; Diminta Beralih ke &quot;E-commerce&quot;' or . = 'TikTok Shop Ditutup Hari Ini, &quot;Seller&quot; Diminta Beralih ke &quot;E-commerce&quot;')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>05aa04dc-c1e3-402a-9af1-759d426ab958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gs-title</value>
      <webElementGuid>981bb96d-ae2c-4758-91b6-88e179a251e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.google.com/url?client=internal-element-cse&amp;cx=partner-pub-9012468469771973:uc7pie-r3ad&amp;q=https://money.kompas.com/read/2023/10/04/080000126/tiktok-shop-ditutup-hari-ini-seller-diminta-beralih-ke-e-commerce-&amp;sa=U&amp;ved=2ahUKEwjvuduAz_iDAxVOTWwGHXjVDrkQFnoECAUQAg&amp;usg=AOvVaw1TfDpvC8VcBDY9cHymiMXw</value>
      <webElementGuid>6391099d-b9fa-4f25-833f-6253d73bbead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_parent</value>
      <webElementGuid>34440284-d434-487d-95ab-563ab0e8a1bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>e94f072e-1976-4e97-a01a-15fcb0518c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cturl</name>
      <type>Main</type>
      <value>https://www.google.com/url?client=internal-element-cse&amp;cx=partner-pub-9012468469771973:uc7pie-r3ad&amp;q=https://money.kompas.com/read/2023/10/04/080000126/tiktok-shop-ditutup-hari-ini-seller-diminta-beralih-ke-e-commerce-&amp;sa=U&amp;ved=2ahUKEwjvuduAz_iDAxVOTWwGHXjVDrkQFnoECAUQAg&amp;usg=AOvVaw1TfDpvC8VcBDY9cHymiMXw</value>
      <webElementGuid>8935df63-acd4-4fbc-90e4-c46f778fd4a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctorig</name>
      <type>Main</type>
      <value>https://money.kompas.com/read/2023/10/04/080000126/tiktok-shop-ditutup-hari-ini-seller-diminta-beralih-ke-e-commerce-</value>
      <webElementGuid>88c69c4b-7221-4e11-afbd-5f52e5368e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TikTok Shop Ditutup Hari Ini, &quot;Seller&quot; Diminta Beralih ke &quot;E-commerce&quot;</value>
      <webElementGuid>288aa500-51fe-41ce-b530-b861774bb217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;___gcse_0&quot;)/div[@class=&quot;gsc-control-cse gsc-control-cse-en&quot;]/div[@class=&quot;gsc-control-wrapper-cse&quot;]/div[@class=&quot;gsc-results-wrapper-nooverlay gsc-results-wrapper-visible&quot;]/div[@class=&quot;gsc-wrapper&quot;]/div[@class=&quot;gsc-resultsbox-visible&quot;]/div[@class=&quot;gsc-resultsRoot gsc-tabData gsc-tabdActive&quot;]/div[@class=&quot;gsc-results gsc-webResult&quot;]/div[@class=&quot;gsc-expansionArea&quot;]/div[@class=&quot;gsc-webResult gsc-result&quot;]/div[@class=&quot;gs-webResult gs-result&quot;]/div[@class=&quot;gsc-thumbnail-inside&quot;]/div[@class=&quot;gs-title&quot;]/a[@class=&quot;gs-title&quot;]</value>
      <webElementGuid>01f473c7-5073-4e92-8c05-fa51921ee4e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='___gcse_0']/div/div/div/div[5]/div[2]/div/div/div/div[2]/div/div/div/a</value>
      <webElementGuid>3f86ce9d-fdb4-454c-82dd-b4b1641833ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tiktok'])[2]/following::a[1]</value>
      <webElementGuid>67206ffe-4ebf-4388-a999-0ffc810be194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='money.kompas.com'])[1]/preceding::a[1]</value>
      <webElementGuid>942c59fe-6a81-4903-976c-8202b3302d6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Shop Ditutup Hari Ini, &quot;Seller&quot; Diminta Beralih ke &quot;E-commerce&quot;']/parent::*</value>
      <webElementGuid>2eb8827f-2ebd-4eb5-a7f2-e2c404e7c1c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.google.com/url?client=internal-element-cse&amp;cx=partner-pub-9012468469771973:uc7pie-r3ad&amp;q=https://money.kompas.com/read/2023/10/04/080000126/tiktok-shop-ditutup-hari-ini-seller-diminta-beralih-ke-e-commerce-&amp;sa=U&amp;ved=2ahUKEwjvuduAz_iDAxVOTWwGHXjVDrkQFnoECAUQAg&amp;usg=AOvVaw1TfDpvC8VcBDY9cHymiMXw')]</value>
      <webElementGuid>b205f7e7-8f48-45e9-a2a5-5a08b37730be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div/a</value>
      <webElementGuid>c98d0a95-9955-4579-92f4-0585afac871c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.google.com/url?client=internal-element-cse&amp;cx=partner-pub-9012468469771973:uc7pie-r3ad&amp;q=https://money.kompas.com/read/2023/10/04/080000126/tiktok-shop-ditutup-hari-ini-seller-diminta-beralih-ke-e-commerce-&amp;sa=U&amp;ved=2ahUKEwjvuduAz_iDAxVOTWwGHXjVDrkQFnoECAUQAg&amp;usg=AOvVaw1TfDpvC8VcBDY9cHymiMXw' and (text() = 'TikTok Shop Ditutup Hari Ini, &quot;Seller&quot; Diminta Beralih ke &quot;E-commerce&quot;' or . = 'TikTok Shop Ditutup Hari Ini, &quot;Seller&quot; Diminta Beralih ke &quot;E-commerce&quot;')]</value>
      <webElementGuid>3e14b278-180e-4942-943d-09792c051669</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
