<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Login</name>
   <tag></tag>
   <elementGuidId>a0ba9e78-5664-443d-8dbd-949422e95319</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt_signin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='txt_signin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>497e359b-e925-4c6f-ad6d-0c17d00010ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_signin</value>
      <webElementGuid>f46b8daf-9dd3-40ea-b117-5a902622435f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://account.kompas.com/login/a29tcGFz/aHR0cHM6Ly93d3cua29tcGFzLmNvbS8=?_ga=2.68029201.1682013299.1706145460-1425150012.1706145452</value>
      <webElementGuid>d99f1761-9c7f-46ee-9327-236d37039cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Login</value>
      <webElementGuid>edf34f31-d637-405e-8f90-1f2ea9ab51de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_signin&quot;)</value>
      <webElementGuid>cda43673-3e6d-4de5-b504-69df2f616204</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='txt_signin']</value>
      <webElementGuid>b72052a3-b3a3-4930-843f-01141495833f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='sso__item']/a</value>
      <webElementGuid>68a60ca0-9620-4b06-9b32-2cb4666ddf55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Koin'])[1]/following::a[2]</value>
      <webElementGuid>fbe3b393-b68c-4786-9bd3-7233d337b93a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mode Terang'])[1]/following::a[3]</value>
      <webElementGuid>6cca8197-aac1-4dbc-9145-5d21fbc2a6b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gabung Kompas.com+'])[1]/preceding::a[1]</value>
      <webElementGuid>e74e972d-adb9-4d7e-88b3-195a38d28ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://account.kompas.com/login/a29tcGFz/aHR0cHM6Ly93d3cua29tcGFzLmNvbS8=?_ga=2.68029201.1682013299.1706145460-1425150012.1706145452')]</value>
      <webElementGuid>ec942b4a-69d1-4846-94c4-b05dcbf56db2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/ul/li/a</value>
      <webElementGuid>cc61ea1c-cc25-44f8-a362-91bb0e1bed34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'txt_signin' and @href = 'https://account.kompas.com/login/a29tcGFz/aHR0cHM6Ly93d3cua29tcGFzLmNvbS8=?_ga=2.68029201.1682013299.1706145460-1425150012.1706145452' and (text() = ' Login' or . = ' Login')]</value>
      <webElementGuid>85eba786-3be4-473d-9e86-c979768d594d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
