<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_KompasHeader</name>
   <tag></tag>
   <elementGuidId>6fbb2366-10e3-4b40-b1e7-f55ee0934fba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#anni26-img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='anni26-img']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1a7f0db8-61cb-4ea8-a988-834a61bcecdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://asset.kompas.com/data/2023/09/20/kompascom/desktop/images/logo-kompascom-28.png</value>
      <webElementGuid>cbc3a52b-1d7f-43ed-9e8d-20d576678769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>28 Tahun Kompas.com, Jernih Melihat Dunia</value>
      <webElementGuid>17603611-a548-4ec2-9912-4301cd9a395f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>anni26-img</value>
      <webElementGuid>f91eec6d-3d7c-4bd0-be7e-b6d071d3b934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;anni26-img&quot;)</value>
      <webElementGuid>44a93e31-6aa5-49ca-812c-52579a27ce48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='anni26-img']</value>
      <webElementGuid>2d8a7015-2725-45f2-820f-6442b5691ea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='28 Tahun Kompas.com, Jernih Melihat Dunia']</value>
      <webElementGuid>6c51c972-fd4e-49b1-9f58-49f9732a2560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>249ad2f1-5a6f-4af6-866d-121e0f4cc23f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://asset.kompas.com/data/2023/09/20/kompascom/desktop/images/logo-kompascom-28.png' and @alt = '28 Tahun Kompas.com, Jernih Melihat Dunia' and @id = 'anni26-img']</value>
      <webElementGuid>95a69d5e-62b4-4112-bb17-9f2cb5079925</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
