<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_LoginForVerify</name>
   <tag></tag>
   <elementGuidId>4a5530ab-447f-4866-a903-4bd0b25e8143</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.custom_text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='KG Media ID'])[1]/following::p[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>7ca151b4-f6d3-4465-ac49-ea0f51bae7a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom_text</value>
      <webElementGuid>2f4088f4-d776-428e-8625-13cbc3964d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login dengan KG Media ID untuk menggunakan layanan-layanan dari KG Media.</value>
      <webElementGuid>a6c5ba22-1216-4e29-9dca-a0b1a7e997d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/div[@class=&quot;block-top&quot;]/p[@class=&quot;custom_text&quot;]</value>
      <webElementGuid>feea22f6-a9ab-40b8-83f5-2b190faee909</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KG Media ID'])[1]/following::p[1]</value>
      <webElementGuid>85712822-3089-43e2-bac2-753b202a378d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KG Media ID'])[2]/preceding::p[1]</value>
      <webElementGuid>72d92e0b-2d02-4d2e-ab64-5996c547d1ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::p[1]</value>
      <webElementGuid>cd490126-5682-48ce-8b55-744eca565b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login dengan KG Media ID untuk menggunakan layanan-layanan dari KG Media.']/parent::*</value>
      <webElementGuid>1e5f16cc-2c44-411d-8b89-f446e2327baf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>52752b66-aefe-4f2c-a8fb-e2ba401b04d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Login dengan KG Media ID untuk menggunakan layanan-layanan dari KG Media.' or . = 'Login dengan KG Media ID untuk menggunakan layanan-layanan dari KG Media.')]</value>
      <webElementGuid>affb355f-e56c-48a4-8597-c97057be05e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
